### ISSUE TITLE
Struggles with afterscripts

### ISSUE THREAD

**Issue by Cesar48** [ConSol-Lab/gourd#35]
Hi,

I'm currently working with gourd and I tried to do some postprocessing, specifically through afterscripts (though I could rewrite it to use the postprocessing workflow, or next according to #32, but it seems that would require me to wait for the mentioned documentation).
Currently I've downgraded my script to be exactly what it says in the documentation:

gourd.toml:
```toml
[program.program_name]
binary = "/path/to/binary/pumpkin-cli"
arguments = ["several", "different", "flags"]
afterscript = "./script.sh"
```
script.sh:
```sh
echo $1 > $2
```

However, upon running, I (repeatedly) get the following error message:
```
warn: No output found for afterscript of run #1: caused by: Could not run the afterscript at "/full/correct/path/to/script.sh" with job results at "/full/correct/path/to/experiments/44/0/1/stdout"
 |
 |  help: Check that the afterscript is correct and job results exist at "/full/correct/path/to/experiments/44/0/1/stdout"
 |
 |  Check that the afterscript correctly places the output in a file.
```

What am I missing? Or, perhaps more precisely: is something missing in the documentation? Or did I simply read it wrong?
